# fly.toml app configuration file generated for misty-tree-9392 on 2023-06-30T12:54:51-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "misty-tree-9392"
primary_region = "dfw"

[build]
  image = "Dockerfile"

[http_service]
  internal_port = 4567
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
