source "https://rubygems.org"

gem "awesome_print"
gem "puma"
gem "sinatra"
gem "wkhtmltopdf-binary"
gem "pdfkit"
gem "faraday"
gem "notion-ruby-client"
gem "moneta"
gem "tty-prompt"
gem "tty-spinner"
gem "rackup", "~> 2.1"
