- name: Add To GitHub projects
  uses: actions/add-to-project@v0.4.0
  with:
    # URL of the project to add issues to
    project-url: https://github.com/users/dealingwith/projects/1/
    # A GitHub personal access token with write access to the project
    github-token: ${{ secrets.GITHUB_TOKEN }}
